import { Inject, Injectable } from '@nestjs/common';
import { CreateCreditApplicationInputDto } from '../dto/create-credit-application.input.dto';
import { CreateCreditApplicationOutputDto } from '../dto/create-credit-application.output.dto';
import { CreditApplication } from '../../domain/entities/credit-application.entity';
import { CREDIT_APPLICATION_REPOSITORY_PORT } from '../../domain/ports/credit-application.repository.port';
import type { CreditApplicationRepositoryPort } from '../../domain/ports/credit-application.repository.port';

@Injectable()
export class CreateCreditApplicationUseCase {
    constructor(
        @Inject(CREDIT_APPLICATION_REPOSITORY_PORT)
        private readonly repository: CreditApplicationRepositoryPort,
    ) { }

    async execute(dto: CreateCreditApplicationInputDto): Promise<CreateCreditApplicationOutputDto> {
        // Create a new CreditApplication entity.
        // ID is initially empty as it will be generated by the repository (database).
        const application = new CreditApplication(
            '',
            dto.customerId,
            dto.purpose,
            dto.amount,
            dto.term,
            'PENDING', // Default status
        );

        const savedApplication = await this.repository.save(application);

        return new CreateCreditApplicationOutputDto(
            savedApplication.id,
            savedApplication.customerId,
            savedApplication.purpose,
            savedApplication.amount,
            savedApplication.term,
            savedApplication.status,
        );
    }
}
